### ISSUE TITLE
unable to install on pstv usb hdd

### ISSUE THREAD

**Issue by luke187** [Freakler/vita-AdrenalineEasyInstaller#9]
I am not able to install adrenaline on my pstv on usb hdd on henkaku r10. I did the bubble install and on reboot it is not there even after mounting the hdd. I tried using loco roco demo on the hdd and it installs but after the reboot adrenaline does not work it is still loco roco. Does anyone have any advice on how to get adrenaline working on ps tv using usb hdd as memory card?

**Comment by Freakler** [comment]
As the readme says its not working as of now because of the reboot. It should work with enso or as soon as there is a better method to refresh a bubble. This was stated a 100 times before..

Option 1: What you can do is use the Installer without using "Press X to reboot" and close manually without any rebooting. This will not make your bubble change but Adrenaline should work..

Option 2: Do it manually, or install everything on a real memory card fiirst and then copy the files to your usb hdd.

**Comment by seanp2500** [comment]
This is not true.  See my youtube for video proof...

https://www.youtube.com/watch?v=Ep9D1X6HsmU&t=25s

it was a real pita it took several attempts.  It seems you need it installed first to internal memory and then it will take to usb hd.  Hope this helps!

**Comment by Freakler** [comment]
enso fixes the reboot problem. closed
